### ISSUE TITLE
Remove leading spaces before commands

### ISSUE THREAD

**Issue by Gryllida** [irssi/irssi.github.io#39]
Some files such as `documentation/startup/index.markdown` have IRSSI commands with leading spaces. Some people reading the page copy/paste the command with the space and don't notice the fact until a few minutes later. I believe we can indent these commands with 4 spaces instead of 5 spaces to avoid this issue...

Thanks for Jayha for identifying this issue at #freenode today.

**Comment by ailin-nemui** [comment]
I will close this since you  fixed it
