### ISSUE TITLE
Irssi.org redirect?

### ISSUE THREAD

**Issue by starcraftman** [irssi/irssi.github.io#4]
This new github.io webpage isn't even on the first page of my google results. Does this project no longer control irssi.org? I was just searching for official docs and that old one came up, but not this new github one.

Currently irssi.org just times out.

**Comment by GeertHauwaerts** [comment]
We had an issue with the irssi.org server which has just been resolved; with regards to the script archive, the official URL is http://scripts.irssi.org which is hosted as a GitHub pages site.

Aside from the small downtime of our webserver, everything looks normal to me; tnx for reporting the web server issue! :)

PS: The downtime of the (www).irssi.org server, should not have affected http://scripts.irssi.org; it might have been a temporary issue with CloudFlare DNS as well.

**Comment by starcraftman** [comment]
@GeertHauwaerts Thanks for fixing. I was mainly interested in docs, as I just started using irssi.
