### ISSUE TITLE
redirect themes.irssi.org to new url

### ISSUE THREAD

**Issue by Gryllida** [irssi/irssi.github.io#45]
Hello all (dear webmasters in particular),

May we have a redirect from http://themes.irssi.org to https://irssi-import.github.io/themes/ please? I saw a confused user in another channel just now, they lost the page. At present http://themes.irssi.org opens www.irssi.org homepage, which is suboptimal.

This perhaps could be achieved by editing the webserver configuration.

Regards,
Svetlana

**Comment by dequis** [comment]
Done

@ailin-nemui if you'd prefer you can add a CNAME file and I can remove the redirect to that url.
